export const STRIPE_CLIENT = Symbol('STRIPE_CLIENT');
export const STRIPE_ACCOUNT_SERVICE = Symbol('STRIPE_ACCOUNT_SERVICE');
export const STRIPE_CONNECT_SERVICE = Symbol('STRIPE_CONNECT_SERVICE');
export const STRIPE_PAYMENT_SERVICE = Symbol('STRIPE_PAYMENT_SERVICE');
